### ISSUE TITLE
Restructure and simplify FOM interactions

### ISSUE THREAD

**Issue by AMSP-04** [AMSP-04/NETN-TMR#10]
* Remove TMR prefix of TMR (Root) subclasses.
* Remove TransferType parameter and replace with explicit interaction classes
* Add RequestDivestiture, RequestAcquisition, OfferDivestiture, OfferAcquisition, TriggerDivestiture, TriggerAcquisition and TriggerAcquisitionIfAvailable

![NETN-TMR New](https://user-images.githubusercontent.com/50767029/62036149-877f1c80-b1f1-11e9-9af5-4b01233d63f9.png)

participant Trigger
participant Request
participant Response
participant RTI

autonumber 

== Divestiture ==
Trigger ->> Request:TriggerDivestiture(id, attributes)

Request ->> Response:RequestDivestiture(id, attributes)

Response->>Request:OfferAcquisition(id, attributes)

group HLA Services

Response->>RTI: attributeOwnershipAcquisition()
RTI->>Request: requestAttributeOwnershipRelease()
Request->>RTI: updateAttributeValues()
RTI->>Response: reflectAttributeValues()
Request->>RTI: attributeOwnershipDivestitureIfWanted()
RTI->>Response: attributeOwnershipAcquisitionNotification()
end

== Acquisition ==

Trigger ->> Request:TriggerAcquisition(id, attributes)

Request ->> Response:RequestAcquisition(id, attributes)

Response->>Request:OfferDivestiture(id, attributes)

group HLA Services

Request->>RTI: attributeOwnershipAcquisition()
RTI->>Response: requestAttributeOwnershipRelease()
Response->>RTI: updateAttributeValues()
RTI->>Request: reflectAttributeValues()
Response->>RTI: attributeOwnershipDivestitureIfWanted()
RTI->>Request: attributeOwnershipAcquisitionNotification()
end

== Acquisition If Available==

Trigger ->> Request:TriggerAcquisitionIfAvailable(id, attributes)

group HLA Services

Request->>RTI: attributeOwnershipAcquisitionIfAvailable()

RTI->>Request: attributeOwnershipAcquisitionNotification()
end
autonumber off

**Comment by lofstrandbjorn** [comment]
Decision needed

**Comment by lofstrandbjorn** [comment]
* Changed InteractionClass `TMR_OfferTransferModellingResponsibility` to `OfferTransfer`
* Changed InteractionClass `TMR_RequestTransferModellingResponsibility` to `RequestTransfer`
* Changed InteractionClass `TMR_CancelRequest` to `CancelRequest`
* Changed InteractionClass `TMR_TransferResult` to `TransferResult`
* Changed InteractionClass `TMR_InitiateTransferModellingResponsibility` to `InitiateTransfer`
