### ISSUE TITLE
Naming of datatype NoofferReasonEnum32 and Enumeration OwnershipStateNotApplicableWithRequest

### ISSUE THREAD

**Issue by AMSP-04** [AMSP-04/NETN-TMR#11]
Correct language. 

NoOffer...
OwnershipStateNotApplicableToRequest (or ...NotCompatibleWith...)

**Comment by lofstrandbjorn** [comment]
* Changed name of EnumeratedDatatype `NoofferReasonEnum32` to `NoOfferReasonEnum32`
