### ISSUE TITLE
Update use of parameters RequestFederate, ResponseFederate and Initiating

### ISSUE THREAD

**Issue by AMSP-04** [AMSP-04/NETN-TMR#13]

**Comment by lofstrandbjorn** [comment]
* Remove parameter ´Initiating´ of interaction class ´TMR_InitiateTransferModellingResponsibility´
* Move parameter ´RequestingFederate´ from interaction class ´TMR´ to ´TMR_InitiateTransferModellingResponsibility´

**Comment by lofstrandbjorn** [comment]
* Remove parameter `Initiating` of interaction class `TMR_InitiateTransferModellingResponsibility`
* Move parameter `RequestingFederate` from interaction class `TMR` to `TMR_InitiateTransferModellingResponsibility`
