### ISSUE TITLE
Tags element in FOM module causes merge issue with RPR 2.0

### ISSUE THREAD

**Issue by bergtwvd** [AMSP-04/NETN-TMR#16]
Both RPR 2.0 and NETN TMR have a tags element. These have different content, with a FOM merge issue as result.
Quick solution is to remove to tags element in the NETN TMR FOM module.

**Comment by lofstrandbjorn** [comment]
We will remove tag elements from NETN TMR,

**Comment by lofstrandbjorn** [comment]
New NETN-TMR v3 is a major simplification of the TMR pattern(s). Use of TAGs is removed.
