### ISSUE TITLE
Rename objectClass TMR to TMR_Root or TMR_Base

### ISSUE THREAD

**Issue by AMSP-04** [AMSP-04/NETN-TMR#5]
Align with naming convention used in other NETN modules.

**Comment by lofstrandbjorn** [comment]
Use TMR_Root and remove TMR prefix of leaf interaction classes. Rename/simplify name of ineteractions,

**Comment by lofstrandbjorn** [comment]
Add a MRM_Root. Put all MRM classes under the root. Rename MRM_Object to MRM_Service. Remove MRM prefix of leaf interction classes.

**Comment by lofstrandbjorn** [comment]
* Changed InteractionClass `TMR` to `TMR_Service`
* Changed InteractionClass `TMR_OfferTransferModellingResponsibility` to `OfferTransfer`
* Changed InteractionClass `TMR_RequestTransferModellingResponsibility` to `RequestTransfer`
* Changed InteractionClass `TMR_CancelRequest` to `CancelRequest`
* Changed InteractionClass `TMR_TransferResult` to `TransferResult`
* Changed InteractionClass `TMR_InitiateTransferModellingResponsibility` to `InitiateTransfer`

**Comment by lofstrandbjorn** [comment]
* Changed InteractionClass `TMR` to `TMR_Interaction` and renamed parameter `TransactionID` to `TransferId`
