### ISSUE TITLE
Drop or clarify use of capabilityType parameter.

### ISSUE THREAD

**Issue by AMSP-04** [AMSP-04/NETN-TMR#6]

**Comment by lofstrandbjorn** [comment]
* Remove Parameter `CapabilityType` from InteractionClass `TMR_RequestTransferModellingResponsibility`
* Remove Parameter `CapabilityType` from InteractionClass `TMR_InitiateTransferModellingResponsibility`
* Remove EnumeratedDatatype `CapabilityTypeEnum32`
